version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root